{{- $baseSettings := include "jupiter.applicationSettings" . | fromYaml -}}
{{- $overrides := include "storage.settings" . | fromYaml -}}
{{- $newDict := merge $overrides $baseSettings -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  appsettings.Local.yaml: |
{{ $newDict | toYaml | indent 4 }} 

{{- define "storage.settings" -}}
{{- $serviceBaseName := .Release.Name | lower -}}
{{- $config := .Values.config | default dict -}}
{{- $replication := $config.Replication | default dict -}}
{{- $filesystem := $config.Filesystem | default dict -}}
Horde_Storage:
{{ if .Values.worker.enabled }}
  # if using the workers we do not attempt to participate in the leader election as a normal deployment
  LeaderElectionImplementation: "Static"
{{ else }}
  LeaderElectionImplementation: "Kubernetes"
{{ end }}
  ReferencesDbImplementation:  {{ default "Scylla" $config.ReferencesDbImplementation }}
  ReplicationLogWriterImplementation:  {{ default "Scylla" $config.ReplicationLogWriterImplementation }}
  ContentIdStoreImplementation :  {{ default "Scylla" $config.ContentIdStoreImplementation }}
  BlobIndexImplementation :  {{ default "Scylla" $config.BlobIndexImplementation }}

{{- if $config.EnableLastAccessTracking -}}
  EnableLastAccessTracking: {{ $config.EnableLastAccessTracking }}
{{- end -}}

{{ if $config.StorageImplementations }}
  StorageImplementations:
  {{- range $config.StorageImplementations -}}
  - {{ . }}
  {{- end -}}
{{ else }}
  StorageImplementations:
  {{- if or (.Values.persistence.enabled) (.Values.persistence.volume) }}
  - "FileSystem"
  {{- end -}}
  {{- if and (.Values.global.cloudProvider) (eq .Values.global.cloudProvider "Azure") }}
  - "Azure"
  {{- else if and (.Values.global.cloudProvider) (eq .Values.global.cloudProvider "AWS") }}
  - "S3"
  {{- else -}}
  {{- fail "You have to specify a cloud provider as global.cloudProvider"}}
  {{- end -}}
{{- end }}

{{- if $config.Jupiter }}
Jupiter: 
{{ $config.Jupiter | toYaml | nindent 2 }}
{{- end }}

Replication:
  Enabled: {{ default "false" $replication.Enabled }}
{{ with $replication.Replicators }}
  Replicators:
{{ range . }}
  - ReplicatorName: {{ required "ReplicatorName must be specified for a replicator" .ReplicatorName }}
    NamespaceToReplicate: {{ required "Namespace must be specified for a replicator" .Namespace }}
    ConnectionString: {{ required "replication remote connection string has to be specified" .ConnectionString }}
    MaxParallelReplications: {{ default 64  .MaxParallelReplications }}
    SkipSnapshot: {{ default true  .SkipSnapshot }}
{{- end -}}
{{- end }}

{{- if $config.ConsistencyCheck }}
ConsistencyCheck: 
{{ $config.ConsistencyCheck | toYaml | nindent 2 }}
{{- end }}

{{- if $config.GC }}
GC: 
{{ $config.GC | toYaml | nindent 2 }}

{{- if or (.Values.persistence.enabled) (.Values.persistence.volume) }}
  RunFilesystemCleanup: true
{{- end }}
{{- end }}

{{- if or (.Values.persistence.enabled) (.Values.persistence.volume) }}
FileSystem:
  RootDir:  {{ printf "%s/Blobs" .Values.persistence.mountPath }}
  MaxSizeBytes: {{ required "MaxSizeBytes of the cache volume must be specified" $filesystem.MaxSizeBytes }}
 {{- if $filesystem.TriggerThresholdPercentage }}
  TriggerThresholdPercentage: {{ $filesystem.TriggerThresholdPercentage }}
{{- end }}
{{- if $filesystem.TargetThresholdPercentage }}
  TargetThresholdPercentage: {{ $filesystem.TargetThresholdPercentage }}
{{- end }}
{{- end }}

{{- if $config.Scylla }}
Scylla: 
{{ $config.Scylla | toYaml | nindent 2 }}
{{- end }}

{{- if $config.Serilog }}
Serilog: 
{{ $config.Serilog | toYaml | nindent 2 }}
{{- end }}

{{- if and (.Values.global.cloudProvider) (eq .Values.global.cloudProvider "Azure") }}
{{ include "cloud.settings.azure" .Values }}
{{- else if and (.Values.global.cloudProvider) (eq .Values.global.cloudProvider "AWS") }}
{{ include "cloud.settings.aws" .Values }}
{{- else -}}
{{- fail "You have to specify a cloud provider as global.cloudProvider"}}
{{- end }}

{{ end }}

{{- define "cloud.settings.azure" -}}
{{- $config := .config -}}
{{- $azure := default dict $config.Azure -}}
Azure:
  ConnectionString: {{ required "Blob Storage connection string has to be specified" $azure.ConnectionString }}
{{ end }}

{{- define "cloud.settings.aws" -}}
{{- $config := .config -}}
{{- $s3 := default dict $config.S3 -}}
S3:
  ConnectionString: "AWS"
  BucketName: {{ required "The name of the S3 bucket to use has to be specified" $s3.BucketName }}
  # We assume that you are creating your buckets yourself for production deployments like this 
  CreateBucketIfMissing: {{ default  false $s3.CreateBucketIfMissing }}
  SetBucketPolicies: {{ default false $s3.SetBucketPolicies }}

  UseBlobIndexForExistsCheck: {{ default false $s3.UseBlobIndexForExistsCheck }}
{{ end }}

