{{- if .Values.ingress.enabled }}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if .Values.ingress.class }}
  ingressClassName: {{ .Values.ingress.class }}
  {{- end }}
  {{- if .Values.secretStore.enabled }}
  {{- if .Values.ingress.hostname }}
  tls:
    - hosts:
      - {{ .Values.ingress.hostname }}
      secretName: {{ .Values.ingress.tlsSecretName }}
    {{- range .Values.ingress.extraHosts }}
    - hosts:
      - {{ .hostName }}
      secretName: {{ .tlsSecretName }}
    {{- end }}
  {{- end }}
  {{- end }}
  rules:
    {{- if .Values.ingress.hostname }}
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          {{- range .Values.ingress.extraPaths }}
          - path: {{ .path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" $) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: {{- default (include "common.names.fullname" $) .name }}
                port:
                  # THE_COALITION_CHANGE (manuvar@microsoft.com) - BEGIN Configure ingress port number
                  number: {{- default 80 .port }}
                  # THE_COALITION_CHANGE (manuvar@microsoft.com) - END Configure ingress port number
          {{- end }}
          - path: {{ .Values.ingress.path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" .) }}
            pathType: {{ .Values.ingress.pathType }}
            {{- end }}
            backend:
              service:
                name: {{ include "common.names.fullname" . }}
                port:
                  # THE_COALITION_CHANGE (manuvar@microsoft.com) - BEGIN Configure ingress port number
                  number: {{ default 80 .Values.ingress.port }}
                  # THE_COALITION_CHANGE (manuvar@microsoft.com) - BEGIN Configure ingress port number
    {{- end }}
    {{- range .Values.ingress.extraHosts }}
    - host: {{ .hostName }}
      http:
        paths:
          - path: {{ default "/" .path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" $) }}
            pathType: {{ default "ImplementationSpecific" .pathType }}
            {{- end }}
            backend:
              service:
                name: {{ default (include "common.names.fullname" $) .serviceName }}
                port:
                  # THE_COALITION_CHANGE (manuvar@microsoft.com) - BEGIN Configure ingress port number
                  number: {{ default 80 .port }}
                  # THE_COALITION_CHANGE (manuvar@microsoft.com) - BEGIN Configure ingress port number
    {{- end }}
{{- end }}