{{- if and .Values.secretStore.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ default "horde-secret-provider" .Values.secretStore.secretProviderName }}
spec:
  provider: azure
  secretObjects:
    - secretName: {{ .Values.ingress.tlsSecretName }}
      type: kubernetes.io/tls
      data:
        - objectName: {{ .Values.ingress.tlsCertName }}
          key: tls.key
        - objectName: {{ .Values.ingress.tlsCertName }}
          key: tls.crt
    {{- range .Values.ingress.extraHosts }}
    - secretName: {{ .tlsSecretName }}
      type: kubernetes.io/tls
      data:
        - objectName: {{ .tlsCertName }}
          key: tls.key
        - objectName: {{ .tlsCertName }}
          key: tls.crt
    {{- end }}
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    {{ with .Values.secretStore }}
    clientID: {{ .clientID | quote }}
    keyvaultName: {{ .keyvaultName | quote }}
    resourceGroup: {{ .resourceGroup | quote }}
    subscriptionId: {{ .subscriptionId | quote }}
    tenantId: {{ .tenantId | quote }}
    {{ end }}
    cloudName: ""
    cloudEnvFileName: ""
    objects:  |
      array:
        - |
          objectName: {{ .Values.ingress.tlsCertName }}
          objectType: secret
      {{- range .Values.ingress.extraHosts }}
        - |
          objectName: {{ .tlsCertName }}
          objectType: secret
      {{- end }}
  {{- end }}
