# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: Deployment
on:
  workflow_dispatch:
  release:
  push:
    branches: main
    paths:
      - configs/*/parameters.json
      - main.bicep

jobs:
  changed-files:
    runs-on: ubuntu-latest

    outputs:
      matrix: "${{ steps.jobs.outputs.matrix }}"
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: nahsi/files-to-matrix@v1
      id: jobs
      with:
        files: configs/*/parameters.json
        settings: >-
          [
            {
              "name": "dir",
              "level": 0
            },
            {
              "name": "studio",
              "level": 1
            },
            {
              "name": "file",
              "level": 2
            }
          ]            

  DeployTemplate:
    runs-on: ubuntu-latest
    needs: changed-files
    environment: ${{ matrix.tf.studio }}
    strategy:
      fail-fast: false
      matrix:
        tf: "${{ fromJSON(needs.changed-files.outputs.matrix) }}"

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run Changed Deployment Script
      run: |
        ${PWD}/scripts/deploy.sh "${{ matrix.tf.dir }}/${{ matrix.tf.studio }}/${{ matrix.tf.file }}" "${{ secrets.AAD_SECRET }}"
