# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: Deployment
on:
  workflow_dispatch:
  release:
  push:
    branches:
      main

jobs:
  DeployTemplate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get specific changed files
      id: changed-files-specific
      uses: tj-actions/changed-files@v31
      with:
        files: |
          configs/*.parameters.json
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run Changed Deployment Script
      if: github.event_type != 'push'
      run: |
        for file in configs/*.parameters.json; do        
          LOCATION=$(jq '.parameters.location.value' "$file")
          RESOURCE_GROUP=$(jq '.metadata.value' "$file")
          ${PWD}/scripts/deploy $LOCATION $RESOURCE_GROUP "$file"
        done

    - name: Run Deployment Script
      if: github.event_type == 'push'
      run: |
        for file in ${{ steps.changed-files.outputs.modified_files }}; do        
          LOCATION=$(jq '.parameters.location.value' "$file")
          RESOURCE_GROUP=$(jq '.metadata.value' "$file")
          ${PWD}/scripts/deploy $LOCATION $RESOURCE_GROUP "$file"
        done
