# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: Pull Request
on:
  pull_request:

concurrency: 
  group: deploy-${{ github.head_ref }}

jobs:
  DeployTemplate:
    runs-on: ubuntu-latest
    environment: canary
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Run Deployment Script
      run: |
        ${PWD}/scripts/deploy.sh main.parameters.json
        ${PWD}/scripts/completeDeployment.sh main.parameters.json
