# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: Pull Request
on:
  pull_request:

concurrency: 
  group: deploy-${{ github.head_ref }}

jobs:
  DeployTemplate:
    runs-on: ubuntu-latest
    environment: canary
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get specific changed files
      id: changed-files-specific
      uses: tj-actions/changed-files@v31
      with:
        files: |
          configs/*/parameters.json
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run Deployment Script
      run: |
        for file in ${{ steps.changed-files.outputs.modified_files }}; do
          ${PWD}/scripts/deploy "$file"
        done
