# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: Run Load Test
on:
  pull_request:

concurrency: 
  group: deploy-${{ github.head_ref }}

jobs:
  DeployTemplate:
    runs-on: ubuntu-latest
    environment: canary

    steps:
    - uses: actions/checkout@v3
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run Load Tests
      run: |
        cd tests
        tar -xf vegeta_12.8.4_linux_386.tar

        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt

        python3 main.py --verbose --seed --host https://preview.thecoalition.horde-storage.gaming.azure.com all || exit 1
