on:
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Template Repository Sync
        uses: EuphoricSystems/action-sync-template-repository@v1.9.1
        with:
          github-token: ${{ secrets.PAT }}
