on:
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Template Repository Sync
        uses: ahmadnassri/action-template-repository-sync@v2.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
