on:
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v0.4.2-draft
        with:
          github_token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          source_repo_path: microsoft/unreal-cloud-ddc-on-azure
